"use client";

import { useState } from "react";
import type { ReactNode } from "react";
import Link from "next/link";
import { Avatar } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { SlideOver } from "@/components/ui/slide-over";
import { Table, TableBody, TableCell, TableHeader, TableRow } from "@/components/ui/table";

function Section({ eyebrow, title, children }: { eyebrow: string; title: string; children: ReactNode }) {
  return <section className="border-t border-[var(--line)] pt-8"><p className="text-[var(--text-xs)] font-semibold uppercase tracking-[0.18em] text-[var(--accent-deep)]">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.03em]">{title}</h2><div className="mt-6">{children}</div></section>;
}

export default function DesignSystemDemo() {
  const [dialogOpen, setDialogOpen] = useState(false);
  const [slideOpen, setSlideOpen] = useState(false);

  return <main className="min-h-screen px-6 py-8 sm:px-10 lg:px-16"><div className="mx-auto max-w-6xl">
    <header className="flex flex-col justify-between gap-5 border-b border-[var(--line)] pb-10 sm:flex-row sm:items-end"><div><Link href="/" className="text-[var(--text-xs)] font-semibold uppercase tracking-[0.16em] text-[var(--accent-deep)]">← recruiting desk</Link><p className="mt-8 text-[var(--text-xs)] font-semibold uppercase tracking-[0.2em] text-[var(--accent-deep)]">Northstar foundation</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">Design system</h1><p className="mt-4 max-w-xl text-sm leading-6 text-[var(--ink-muted)]">A compact, low-fatigue toolkit for triaging applicants quickly. Every control has a visible focus state and every status uses a distinct semantic color.</p></div><span className="font-mono text-xs text-[var(--ink-muted)]">v0.1 / light mode</span></header>

    <div className="space-y-16 py-12">
      <Section eyebrow="Tokens" title="Type, spacing, and surfaces"><div className="grid gap-8 lg:grid-cols-2"><div className="space-y-4"><p className="text-[var(--text-xs)] uppercase tracking-[0.16em] text-[var(--ink-muted)]">Type scale</p><div className="space-y-3"><p className="text-[var(--text-2xl)] font-semibold tracking-[-0.04em]">Display / 36</p><p className="text-[var(--text-xl)] font-semibold tracking-[-0.03em]">Heading / 24</p><p className="text-[var(--text-lg)] font-medium">Lead / 18</p><p className="text-[var(--text-md)]">Body / 15</p><p className="text-[var(--text-sm)]">Supporting / 13</p><p className="text-[var(--text-xs)] uppercase tracking-[0.16em]">Meta / 11</p></div></div><div><p className="text-[var(--text-xs)] uppercase tracking-[0.16em] text-[var(--ink-muted)]">Spacing, material, and shadows</p><div className="mt-4 grid grid-cols-4 gap-3">{["1", "2", "3", "4", "6", "8", "10", "12"].map((step) => <div key={step} className="border border-[var(--line)] bg-[var(--surface)] p-3 text-center text-xs"><div className="mx-auto bg-[var(--accent)]" style={{ height: `var(--space-${step})`, width: `var(--space-${step})` }} /><p className="mt-2">space-{step}</p></div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="ui-material border border-white/60 p-5 shadow-[var(--shadow-panel)]"><p className="text-xs font-medium">Material layer</p></div><div className="border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[var(--shadow-panel)]"><p className="text-xs">Panel shadow</p></div><div className="border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[var(--shadow-dialog)]"><p className="text-xs">Dialog shadow</p></div></div></div></div></Section>

      <Section eyebrow="Pipeline" title="Semantic status colors"><div className="flex flex-wrap gap-2">{([["new", "New"], ["screening", "Screening"], ["phone", "Phone screen"], ["interview", "Interview"], ["offer", "Offer"], ["hired", "Hired"], ["rejected", "Rejected"], ["withdrawn", "Withdrawn"]] as const).map(([tone, label]) => <Badge key={tone} tone={tone}>{label}</Badge>)}</div></Section>

      <Section eyebrow="Controls" title="Buttons, fields, and identity"><div className="grid gap-8 lg:grid-cols-2"><div><p className="mb-3 text-xs uppercase tracking-[0.16em] text-[var(--ink-muted)]">Buttons</p><div className="flex flex-wrap items-center gap-3"><Button size="sm">Small action</Button><Button>Primary action</Button><Button size="lg" variant="outline">Outline action</Button><Button variant="quiet">Quiet action</Button><Button variant="danger">Reject</Button><Button disabled>Disabled</Button></div></div><div><p className="mb-3 text-xs uppercase tracking-[0.16em] text-[var(--ink-muted)]">Badges and avatars</p><div className="flex items-center gap-4"><Avatar name="Ada Lovelace" size="lg" /><Avatar name="Grace Hopper" size="md" /><Avatar name="Alan Turing" size="sm" /><Badge tone="success">Parsed</Badge><Badge tone="warning">Needs review</Badge></div></div><div><Input label="Candidate email" name="email" placeholder="name@example.com" required hint="Supporting helper text." /><div className="mt-5"><Input label="Invalid email" name="invalid" defaultValue="not-an-email" error="Enter a valid email address." /></div></div><Select label="Application status" name="status" defaultValue="SCREENING"><option value="NEW">New</option><option value="SCREENING">Screening</option><option value="INTERVIEW">Interview</option></Select></div></Section>

      <Section eyebrow="Data display" title="Table and empty state"><div className="grid gap-8 lg:grid-cols-[1.25fr_0.75fr]"><Table><TableHeader><TableRow><TableCell header>Candidate</TableCell><TableCell header>Role</TableCell><TableCell header>Status</TableCell></TableRow></TableHeader><TableBody><TableRow><TableCell><div className="flex items-center gap-3"><Avatar name="Ada Lovelace" size="sm" /><span>Ada Lovelace</span></div></TableCell><TableCell>Software engineer</TableCell><TableCell><Badge tone="interview">Interview</Badge></TableCell></TableRow><TableRow><TableCell><div className="flex items-center gap-3"><Avatar name="Grace Hopper" size="sm" /><span>Grace Hopper</span></div></TableCell><TableCell>Platform lead</TableCell><TableCell><Badge tone="screening">Screening</Badge></TableCell></TableRow></TableBody></Table><EmptyState title="No saved searches" description="Saved searches will appear here once your team starts organizing recurring views." action={{ label: "Create a search" }} /></div></Section>

      <Section eyebrow="Overlays" title="Dialog and slide-over"><div className="flex flex-wrap gap-3"><Button onClick={() => setDialogOpen(true)}>Open dialog</Button><Button variant="outline" onClick={() => setSlideOpen(true)}>Open slide-over</Button></div><Dialog open={dialogOpen} onOpenChange={setDialogOpen} title="Reject application" description="This is a centered modal for an occasional decision."><div className="space-y-4"><Select label="Reason" name="reason" required><option value="">Choose a reason</option><option>Not qualified</option><option>Better candidate</option></Select><div className="flex justify-end gap-2"><Button variant="quiet" onClick={() => setDialogOpen(false)}>Cancel</Button><Button variant="danger" onClick={() => setDialogOpen(false)}>Reject</Button></div></div></Dialog><SlideOver open={slideOpen} onOpenChange={setSlideOpen} eyebrow="Candidate detail" title="Ada Lovelace"><div className="space-y-6"><div className="flex items-center gap-3"><Avatar name="Ada Lovelace" size="lg" /><div><p className="font-medium">Ada Lovelace</p><p className="text-sm text-[var(--ink-muted)]">Software engineer</p></div></div><div className="border-t border-[var(--line)] pt-5"><p className="text-xs uppercase tracking-[0.16em] text-[var(--ink-muted)]">Current stage</p><Badge tone="interview">Interview</Badge></div><Button className="w-full" onClick={() => setSlideOpen(false)}>Done</Button></div></SlideOver></Section>
    </div>
  </div></main>;
}